---
- hosts: build
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - raw: apt-get install python -y
    ignore_errors: true

- hosts: build
  become: true
  become_user: root
  pre_tasks:
  - name: include variables
    include_vars: vars/global.yml
  - name: install system specific packages
    include: debian.yml
    when: ansible_os_family == "Debian"
  - name: install RedHat specific packages
    include: redhat.yml
    when: ansible_os_family == "RedHat"
  tasks:
  - name: deploy wily resources
    include: wily.yml
    when: ansible_os_family == "Debian" and not ansible_lsb.codename == "xenial"
  - name: add ssh public key
    authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: update ssh config
    copy: src=files/ssh_config dest=/root/.ssh/config mode=0644
  - name: install docker from upstream
    shell: curl -sSL https://get.docker.io | bash creates=/etc/docker/key.json
  - name: ensure docker is running
    service: name=docker state=started enabled=true
  - name: Install pip based docker-py module
    pip: name=docker-py

  - name: check for vxlan interface
    command: ip -d link
    register: vxlan_info
    ignore_errors: true
  - name: create vxlan interface
    command: ip link add vxlan0 type vxlan id 42 group 239.1.1.1 dev ens3 dstport 4789
    when: not (vxlan_info.stdout | search('vxlan0'))
  - name: create vxlan interface
    command: ip link add vxlan1 type vxlan id 43 group 239.1.1.2 dev ens3 dstport 4789
    when: not (vxlan_info.stdout | search('vxlan1'))
  - name: add ip addr to vxlan0
    command: "ip addr add {{net_0|ipaddr('net')|ipaddr(index)}} dev vxlan0"
    when: not (vxlan_info.stdout | search('vxlan0'))
  - name: add ip addr to vxlan1
    command: "ip addr add {{net_1|ipaddr('net')|ipaddr(index)}} dev vxlan1"
    when: not (vxlan_info.stdout | search('vxlan1'))
  - name: bring up links
    command: ip link set "{{item}}" up
    with_items:
       - vxlan0
       - vxlan1


  - name: Install ansible version 2.0 or greater
    pip: name=pip state=latest
  - name: Install ansible version 2.0 or greater
    pip: name=ansible state=present version=1.9.4
  - name: clone kolla
    git: repo=https://git.openstack.org/openstack/kolla dest=/root/kolla version=stable/mitaka
    ignore_errors: true
  - name: install kolla elements
    pip: name=kolla/ chdir=/root
  - name: update the /etc/kolla directory
    command: cp -r etc/kolla /etc
    args:
      chdir: /root/kolla
      creates: /etc/kolla
  - name: create registry directory if it doesn't exist
    file: state=directory path={{vld}}/registry
  - name: create docker registry compose file
    template: src=templates/registry_yml.j2 dest={{vld}}/docker-compose.yml mode=0644

# certificate for SSL/TLS
  - name: create certs directory if it doesn't exist
    file: state=directory path={{vld}}/certs
  - name: create ssl certs config file for self signed cert
    template: src=templates/openssl_cnf.j2 dest={{vld}}/certs/openssl.cnf mode=0644

  - name: create a self signed CA key
    command: openssl genrsa -out {{vld}}/certs/ca-key.pem 2048 creates={{vld}}/certs/ca-key.pem
  - name: create a signing certificate with our CA key
    command: openssl req -x509 -new -nodes -key {{vld}}/certs/ca-key.pem -days 10000 -out {{vld}}/certs/ca.pem -subj "/CN=registry-ca" creates={{vld}}/certs/ca.pem
  - name: create ca.crt directory for docker
    file: dest=/etc/docker/certs.d/{{ansible_default_ipv4.address}}:4000/ state=directory
  - name: get ca.pem as ca.crt
    fetch: src={{vld}}/certs/ca.pem dest=files/ca.crt flat=yes
  - name: copy ca.crt to docker cert directory
    copy: src=files/ca.crt dest=/etc/docker/certs.d/{{ansible_default_ipv4.address}}:4000/ca.crt

  - name: create ssl key for registery
    command: openssl genrsa -out {{vld}}/certs/domain.key creates={{vld}}/certs/domain.key
  - name: create certificate for key for registry
    command: openssl req -new -key {{vld}}/certs/domain.key -out {{vld}}/certs/domain.csr -subj "/CN=registry" -config {{vld}}/certs/openssl.cnf creates={{vld}}/certs/domain.csr
  - name: sign ssl cert for docker registry
    command: openssl x509 -req -in {{vld}}/certs/domain.csr -CA {{vld}}/certs/ca.pem -CAkey {{vld}}/certs/ca-key.pem -CAcreateserial -out {{vld}}/certs/domain.crt -days 365 -extensions v3_req -extfile {{vld}}/certs/openssl.cnf creates={{vld}}/certs/domain.crt
#  - name: combine pem and csr into crt
#    shell: cat {{vld}}/certs/domain.csr {{vld}}/certs/domain.pem > {{vld}}/certs/domain.crt
  - name: copy the crt to all machines, initially the controller
    fetch: src={{vld}}/certs/domain.crt dest=files/ flat=yes
  - name: upload domain .crt into ca-certificate cache
    copy: src=files/domain.crt dest=/usr/local/share/ca-certificates/{{ansible_hostname}}.crt
  - name: upload ca-certificates
    command: update-ca-certificates

  - name: restart docker
    service: name=docker state=restarted
  - name: check to see if docker registry is running
    command: docker ps
    register: docker_ps
  - name: install docker-compose
    apt: name=docker-compose state=installed
    when: ansible_os_family == "Debian"
  - name: install docker-compose
    yum: name=docker-compose state=installed
    when: ansible_os_family == "RedHat"
  - name: start the docker registry
    command: docker-compose up -d  chdir={{vld}}
    when: "docker_ps.stdout | search('registry') == false"

## address the docker insecure registry so that builds can succeed
  - name: update /etc/default/docker on Ubuntu systems
    lineinfile: dest=/etc/default/docker regexp='^DOCKER_OPTS="(.*)"' line='DOCKER_OPTS="--insecure-registry {{ansible_default_ipv4.address}}:4000"'
    when: ansible_os_family == "Debian"
  - name: create /etc/sysconfig/docker if it does not exist
    file: name=/etc/sysconfig/docker mode=0755 state=touch
    when: ansible_os_family == "RedHat"
  - name: update /etc/sysconfig/docker on CentoOS systems
    lineinfile: dest=/etc/sysconfig/docker regexp='^INSECURE_REGISTRY="(.*)"' line='INSECURE_REGISTRY="--insecure-registry {{ansible_default_ipv4.address}}:4000"' force=yes
    when: ansible_os_family == "RedHat"
  - name: find docker.service
    find: path=/lib/systemd/system pattern='docker.service'
    register: docker_service
  - name: copy docker.service file if it exists
    command: cp /lib/systemd/system/docker.service /etc/systemd/system/docker.service
    when: docker_service.matched
  - name: create docker file if it doesn't already exist
    file: dest=/etc/systemd/system/docker.service state=present mode=0755
    when: not docker_service.matched
  - name: update docker.service file environment file
    ini_file: dest=/etc/systemd/system/docker.service section=Service option=EnvironmentFiles value='-/etc/default/docker'
  - name: update docker.service file execstart
    ini_file: dest=/etc/systemd/system/docker.service section=Service option=ExecStart value='/usr/bin/docker daemon -H fd:// $DOCKER_OPTS'
  - name: create systemd docker service directory
    file: dest=/etc/systemd/system/docker.service.d state=directory
  - name: create docker service conf file
    copy: src=files/kolla.conf dest=/etc/systemd/system/docker.service.d/kolla.conf
  - name: restart daemons
    command: systemctl daemon-reload
  - name: restart docker service
    service: name=docker state=restarted

## Update the /etc/kolla/globals.yml based on the environment
  - name: ensure base is ubuntu
    lineinfile: 'dest=/etc/kolla/globals.yml regexp=^.*kolla_base_distro.* line="kolla_base_distro: ubuntu"'
    when: ansible_os_family == "Debian"
  - name: ensure install type is source
    lineinfile: 'dest=/etc/kolla/globals.yml regexp=^.*kolla_install_type.* line="kolla_install_type: source"'
    when: ansible_os_family == "Debian"
  - set_fact:
      vip_net: "{{ansible_ens3.ipv4.network}}/{{ansible_ens3.ipv4.netmask}}"
  - set_fact:
      vip_ip:  "{{vip_net|ipaddr('net')|ipaddr('-2')|ipaddr('address')}}"
  - name: set the default internal VIP address
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^kolla_internal_vip_address.* line='kolla_internal_vip_address: {{vip_ip}}'"
  - name: set the docker registry address
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*docker_registry:.* line='docker_registry: {{ansible_default_ipv4.address}}:4000'"
  - name: set the docker network interface
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*network_interface:.* line='network_interface: {{pub_int}}'"
  - name: set the docker network interface
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*neutron_external_interface:.* line='neutron_external_interface: veth0'"
  - name: set the docker network interface
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*neutron_plugin_agent:.* line='neutron_plugin_agent: linuxbridge'"


## Ensure DNS is configured
  - name: update resolv.conf with domain
    lineinfile: dest=/etc/resolv.conf backrefs=yes regexp=^search(.*) line='search \1 {{domain}}'
## create and upload an SSH pair
  - name: ensure ssh directory exists
    file: path=~/.ssh state=directory mode=0700
  - name: create ssh keypair
    command: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa creates=~/.ssh/id_rsa
  - name: copy id_rsa to ssh directory
    fetch: src=~/.ssh/id_rsa dest=files/ flat=yes
  - name: fetch the public key
    fetch: src=~/.ssh/id_rsa.pub dest=files/ flat=yes

## Build the images
  - name: run kolla build to build source based images
    shell: 'kolla-build |& tee /var/log/kolla-build.log'
    args:
      creates: /var/log/kolla-build.log
      executable: /bin/bash
    async: 1200
    poll: 0
    register: kolla_build_r
    ignore_errors: true
    when: ansible_os_family == "RedHat"
  - debug: var=kolla_build_r
  - name: run kolla build to build source based images
    shell: 'kolla-build --type source --base ubuntu |& tee /var/log/kolla-build.log'
    args:
      creates: /var/log/kolla-build.log
      executable: /bin/bash
    async: 1200
    poll: 0
    register: kolla_build_u
    ignore_errors: true
    when: ansible_os_family == "Debian"
  - debug: var=kolla_build_u
  - name: check on kolla-build process
    async_status: "jid={{ kolla_build_u.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 600
    when: ansible_os_family == "Debian"
  - name: check on kolla-build process
    async_status: "jid={{ kolla_build_r.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 600
    when: ansible_os_family == "RedHat"
  - debug: msg="kolla-build --type source --base ubuntu --registry {{ansible_default_ipv4.address}}:4000 --push |& tee /var/log/kolla-build.log"
